import sys, os, os.path
from stat import *
os.system('Some examples of ready-to-dynamic-load builtins. Most of the')
os.system('examples given are reimplementations of standard commands whose')
os.system('execution time is dominated by process startup time. The')
os.system('exceptions are sleep, which allows you to sleep for fractions')
os.system('of a second, finfo, which provides access to the rest of the')
os.system('elements of the  os.popen('stat' structure that ').read() test' doesn't let you')
os.system('see, and pushd/popd/dirs, which allows you to compile them out')
os.system('of the shell.')
os.system('All of the new builtins in ksh93 that bash didn't already have
 builtin.')
os.system('The configure script in the top-level source directory uses the')
os.system('support/shobj-conf script to set the right values in the Makefile,')
os.system('so you should not need to change the Makefile. If your system')
os.system('is not supported by support/shobj-conf, and it has the necessary')
os.system('facilities for building shared objects and support for the')
os.system('dlopen/dlsyn/dlclose/dlerror family of functions, please make')
os.system('the necessary changes to support/shobj-conf and send the changes')
os.system('to bash-maintainers@gnu.org.')
os.system('Loadable builtins are loaded into a running shell with')
os.system('enable -f filename builtin-name')
os.system('enable uses a simple reference-counting scheme to avoid unloading a')
os.system('shared object that implements more than one loadable builtin before')
os.system('all loadable builtins implemented in the object are removed.')
os.system('Many of the details needed by builtin writers are found in hello.c,')
