import sys, os, os.path
from stat import *
os.system('/*')
os.system('* realpath -- canonicalize pathnames, resolving symlinks')
os.system('*')
os.system('* usage: realpath [-csv] pathname [pathname...]')
os.system('*')
os.system('* options: -c check whether or not each resolved path exists')
os.system('* -s no output, exit status determines whether path is valid')
os.system('* -v produce verbose output')
os.system('*')
os.system('*')
os.system('* exit status: 0 if all pathnames resolved')
os.system('* 1 if any of the pathname arguments could not be resolved')
os.system('*')
os.system('*')
os.system('* Bash loadable builtin version')
os.system('*')
os.system('* Chet Ramey')
os.system('* chet@po.cwru.edu')
os.system('*/')
os.system('/*')
